[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.primary]
background = "0x1c1c1c"
foreground = "0xc0c0c0"

[cursor]
blink_interval = 500
style = "Underline"
unfocused_hollow = true

[font]
size = 11.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.8

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0
